#spring.application.name=be_shopbangiay
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#
spring:
  application:
    name: be_shopbangiay

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 607810290755-teur38f5l573k25gue4e9igo3kav3l3u.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  datasource:
    url: jdbc:mysql://localhost:3306/dulieugiay?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: f0wqYKZ899yByVqnngHHtgJ11jAQuIJanMaOh6FSfH8=
    expiration: 86400000 # 1 ngày (ms)

  mail:
    host: smtp.gmail.com
    port: 587
    username: 21130582@st.hcmuaf.edu.vn
    password: cdgr oskp fdhi mbqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8443
  ssl:
    key-store: classpath:myshop.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myshop
  servlet:
    context-path: /

logging:
  level:
    org.springframework.security: DEBUG
    com.example.be_shopbangiay: DEBUG

facebook:
  app-id: 1062399375781932
  app-secret: 453b6082e14e4beb2322cfb98dfb69d5
