spring:
  application:
    name: be_shopbangiay

  datasource:
    url: jdbc:mysql://localhost:3306/storegiay
    username: root
    password: tr21092003

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  ssl:
    key-store: classpath:myshop.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myshop
