#spring.application.name=be_shopbangiay
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#
server:
  port: 8443
  ssl:
    key-store: classpath:myshop.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myshop
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/dulieugiay"
    username: root
    password: 123456

  jwt:
    secret: f0wqYKZ899yByVqnngHHtgJ11jAQuIJanMaOh6FSfH8=  # 256-bit base64 encoded
    expiration: 86400000 # 1 ngày (ms)

logging:
  level:
    org.springframework.security: DEBUG
    com.example.be_shopbangiay: DEBUG
facebook:
  app-id: 1062399375781932
  app-secret: 453b6082e14e4beb2322cfb98dfb69d5
