spring:
  application:
    name: be_shopbangiay

  datasource:
    url: jdbc:mysql://localhost:3306/storegiay
    username: root
    password: tr21092003

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: f0wqYKZ899yByVqnngHHtgJ11jAQuIJanMaOh6FSfH8=  # 256-bit base64 encoded
    expiration: 86400000 # 1 ngày (ms)

server:
  port: 8443
  ssl:
    key-store: classpath:myshop.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myshop
